### ISSUE TITLE
`get_lines': undefined method `search' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by nvaken** [bolthar/ruby-hackernews#23]
```
/ruby-hackernews/services/parsers/entry_page_parser.rb:13:in `get_lines': undefined method `search' for nil:NilClass (NoMethodError)
```

Probably related to changes in structure of the HTML? I don't think the children of the `tr`'s are there anymore for the spacers, when changing `entry_page_parser.rb` to the following, everything works as expected.

```
      lines = @page.search("//table")[2].search("tr").select do |tr|
        tr['style'] !~ /height/
      end
```

**Comment by bolthar** [comment]
Hi Niels,

    thanks a lot for the report! This is now fixed, you can either pull from github or install the latest gem version (1.3.6) from Rubygems.
