### ISSUE TITLE
Entry.shows and Entry.jobs bug

### ISSUE THREAD

**Issue by davidesantangelo** [bolthar/ruby-hackernews#26]
undefined method `search' for nil:NilClass
from /Users/davidesantangelo/.rvm/gems/ruby-2.2.1/gems/ruby-hackernews-1.3.7/lib/ruby-hackernews/services/parsers/link_info_parser.rb:10:in `parse'

**Comment by bolthar** [comment]
Hi!

Sorry for the misshap - this should now work as expected. Do not hesitate to let me know if further issues arise :+1:

**Comment by davidesantangelo** [comment]
great thanks!
