### ISSUE TITLE
Error user.login("password")

### ISSUE THREAD

**Issue by lingtorp** [bolthar/ruby-hackernews#29]
Seems like Hacker News has changed their HTML and thus makes some lib break. 

![screen shot 2015-12-07 at 18 22 26](https://cloud.githubusercontent.com/assets/1652130/11634235/9e0b2b7e-9d0f-11e5-8b4f-1d73b257549d.jpg)

**Comment by Entalpi** [comment]
This seems to be in the gem Mechanize, will investigate further.
